hydra:
  run:
    dir: ./

tacto:
  width: 120
  height: 160
  visualize_gui: True

digit:
  urdf_path: "mesh/digit.urdf"
  base_position: [0, 0, 0]

  # quaternion from p.getQuaternionFromEuler([0, -pi/2, 0])
  base_orientation: [0.0, -0.707106, 0.0, 0.707106]
  use_fixed_base: True

object:
  urdf_path: "mesh/sphere_small.urdf"
  base_position: [0, 0, 0]
  global_scaling: 1.0
  use_fixed_base: True
object_control_panel:
  slider_params:
    position_low: [-0.04, -0.02, 0.02]
    position_high: [0.005, 0.02, 0.03]

pybullet_camera:
  cameraDistance: 0.4
  cameraYaw: 0.
  cameraPitch: -89.99
  cameraTargetPosition: [0, 0.01, 2]
